config/routes.rb
Rails.application.routes.draw do

  get '/shop' => 'storefront#index'
  get '/about' => 'storefront#about'
  get '/home' => 'storefront#home'

  devise_for :users
  namespace :admin do
    resources :products
    resources :brands
    resources :categories
  end

  resource :cart, only: [:edit, :destroy]

  resources :line_items, only: [:create, :destroy, :update]
  resources :orders, only: [:new, :create, :show]

  root 'storefront#home'

end

app/models/product.rb
class Product < ActiveRecord::Base
  belongs_to :brand
  belongs_to :category
  has_many :line_items
  before_destroy :ensure_not_referenced_by_any_line_items

  has_attached_file :avatar,
    styles: { large: "500x500#", medium: "300x300#", thumb: "100x100#" },
    default_url: ":style_missing.jpg"
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\Z/

  # By validating brand and category without "_id", we are making sure that they not only have an integer in the brand_id/category_id fields but that those keys refer to real brands and categories that currently exist.
  validates_presence_of :name, :current_price, :quantity, :description, :brand, :category

  validates_numericality_of :current_price, greater_than_or_equal_to: 0.01

  validates_numericality_of :quantity, greater_than_or_equal_to: 0

  def self.search_by_name_or_description(string)
    where("name LIKE ? OR description LIKE ?", "%#{string}%", "%#{string}%")
  end

  private

  # TODO: make sure this works
  def ensure_not_referenced_by_any_line_items
    if line_items.empty?
      return true
    else
      errors.add(:base, "Cannot delete because line items are present")
      return false
    end
  end
end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < AdminController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  # GET /products.json
  def index
    @products = Product.all
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to admin_product_url(@product), notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to admin_product_url(@product), notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to admin_products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:name, :current_price, :quantity, :description, :brand_id, :category_id, :avatar)
    end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/admin/products/_form.html.erb
<%= simple_form_for([:admin, @product]) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :current_price, input_html: {min: 0} %>
    <%= f.input :quantity, input_html: {min: 0} %>
    <%= f.input :description %>
    <%= f.association :brand %>
    <%= f.association :category %>

    <%= f.input :avatar, as: :file, label: "Upload a New Product Image" %>
    <% if @product.avatar.exists? %>
      <%= label_tag "Current Image" %>
      <p><%= image_tag @product.avatar.url(:thumb) %></p>
      <br>
    <% end %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/admin/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form' %>

<%= link_to 'Show', admin_product_path(@product) %> |
<%= link_to 'Back', admin_products_path %>

app/views/admin/products/index.html.erb
<h1>Products</h1>

<table class="table">
  <thead>
    <tr>
      <th colspan="2">Product</th>
      <th>Current price</th>
      <th>Quantity</th>
      <th>Brand</th>
      <th>Category</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td><%= image_tag product.avatar.url(:thumb) %></td>
        <td><%= product.name %></td>
        <td><%= number_to_currency product.current_price %></td>
        <td><%= product.quantity %></td>
        <td><%= product.brand.try(:name) %></td>
        <td><%= product.category.try(:name) %></td>
        <td><%= link_to 'Show', admin_product_path(product) %></td>
        <td><%= link_to 'Edit', edit_admin_product_path(product) %></td>
        <td><%= link_to 'Destroy', admin_product_path(product), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Product', new_admin_product_path %>

app/views/admin/products/new.html.erb
<h1>New Product</h1>

<%= render 'form' %>

<%= link_to 'Back', admin_products_path %>

app/views/admin/products/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @product.name %>
</p>

<p>
  <strong>Current price:</strong>
  <%= number_to_currency @product.current_price %>
</p>

<p>
  <strong>Quantity:</strong>
  <%= @product.quantity %>
</p>

<p>
  <strong>Description:</strong>
  <%= @product.description %>
</p>

<p>
  <strong>Brand:</strong>
  <%= @product.brand.try(:name) %>
</p>

<p>
  <strong>Category:</strong>
  <%= @product.category.try(:name) %>
</p>

<p>
  <%= image_tag @product.avatar.url(:large) %>
</p>

<%= link_to 'Edit', edit_admin_product_path(@product) %> |
<%= link_to 'Back', admin_products_path %>