config/routes.rb
Rails.application.routes.draw do

  get '/shop' => 'storefront#index'
  get '/about' => 'storefront#about'
  get '/home' => 'storefront#home'

  devise_for :users
  namespace :admin do
    resources :products
    resources :brands
    resources :categories
  end

  resource :cart, only: [:edit, :destroy]

  resources :line_items, only: [:create, :destroy, :update]
  resources :orders, only: [:new, :create, :show]

  root 'storefront#home'

end

app/models/brand.rb
class Brand < ActiveRecord::Base
  has_many :products

  validates_uniqueness_of :name
end

app/models/cart.rb
class Cart < ActiveRecord::Base
  has_many :line_items, dependent: :destroy

  def subtotal
    # SQL version of summing which is faster than Ruby
    line_items.select("SUM(quantity * price) AS sum")[0].sum

    # Ruby version of summing
    # line_items.to_a.sum{ |item| item.total }
  end

  def add_product(product_id)
    product = Product.find(product_id)

    # Find out if this product is already in cart. If not, current_item will be nil
    current_item = line_items.find_by(product_id: product_id)

    # If current_item does exist in cart, increase the quantity. If not, build the new line item.
    if current_item
      current_item.quantity += 1
    else
      current_item = line_items.build(product: product, price: product.current_price)
    end
    current_item
  end
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :products

  validates_uniqueness_of :name
end

app/models/line_item.rb
class LineItem < ActiveRecord::Base
  belongs_to :product
  belongs_to :cart
  belongs_to :order

  # TODO: before save, reduce product inventory quantity
  # TODO: before delete/destroy, add back to the product inventory quantity

  def total
    price * quantity
  end
end

app/models/order.rb
class Order < ActiveRecord::Base
  belongs_to :user
  has_many :line_items

  validates_presence_of :shipping_name, :shipping_address, :payment_type

  PAYMENT_TYPES = ["Monopoly Money", "Doubloons", "Credit Card", "Paypal", "Bitcoins"]
  validates_inclusion_of :payment_type, in: PAYMENT_TYPES

  def add_line_items_from_cart(cart_id)
    Cart.find(cart_id).line_items.each do |item|
      item.cart_id = nil
      line_items << item
    end
  end

  def subtotal
    # SQL version of summing which is faster than Ruby
    line_items.select("SUM(quantity * price) AS sum")[0].sum

    # Ruby version of summing
    # line_items.to_a.sum{ |item| item.total }
  end
end

app/models/product.rb
class Product < ActiveRecord::Base
  belongs_to :brand
  belongs_to :category
  has_many :line_items
  before_destroy :ensure_not_referenced_by_any_line_items

  has_attached_file :avatar,
    styles: { large: "500x500#", medium: "300x300#", thumb: "100x100#" },
    default_url: ":style_missing.jpg"
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\Z/

  # By validating brand and category without "_id", we are making sure that they not only have an integer in the brand_id/category_id fields but that those keys refer to real brands and categories that currently exist.
  validates_presence_of :name, :current_price, :quantity, :description, :brand, :category

  validates_numericality_of :current_price, greater_than_or_equal_to: 0.01

  validates_numericality_of :quantity, greater_than_or_equal_to: 0

  def self.search_by_name_or_description(string)
    where("name LIKE ? OR description LIKE ?", "%#{string}%", "%#{string}%")
  end

  private

  # TODO: make sure this works
  def ensure_not_referenced_by_any_line_items
    if line_items.empty?
      return true
    else
      errors.add(:base, "Cannot delete because line items are present")
      return false
    end
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :orders
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  before_action :authenticate_user!
  before_action :require_admin_user
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  include CurrentCart
  before_action :set_cart

  def edit
  end

  def destroy
    if @cart.destroy
      session[:cart_id] = nil
      flash[:notice] = "Cart successfully deleted."
      redirect_to shop_url
    else
      flash[:alert] = "Could not delete cart."
      redirect_to edit_cart_url
    end
  end
end

app/controllers/line_items_controller.rb
class LineItemsController < ApplicationController
  include CurrentCart
  before_action :set_cart

  def create
    product = Product.find(params[:product_id])
    @line_item = @cart.add_product(product.id)

    if @line_item.save
      flash[:notice] = "#{product.name} was successfully added to your cart!"
      redirect_to edit_cart_path(@cart)
    else
      flash.now[:alert] = "Could not add item to your cart."
      redirect_to :back
    end
  end

  def update
    @line_item = @cart.line_items.find(params[:id])

    if @line_item.quantity <= 0
      @line_item.destroy
      redirect_to edit_cart_path(@cart), notice: "Item removed from cart."
    elsif @line_item.update(line_item_params)
      redirect_to edit_cart_path(@cart), notice: "#{@line_item.product.name} quantity updated."
    else
      redirect_to edit_cart_path(@cart), alert: "Could not update quantity."
    end
  end

  def destroy
    @line_item = @cart.line_items.find(params[:id])
    if @line_item.destroy
      redirect_to edit_cart_path(@cart), notice: "Item removed from cart."
    else
      redirect_to @cart, alert: "Could not remove item from cart."
    end
  end

  private

  def line_item_params
    params.require(:line_item).permit(:quantity)
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  include CurrentCart
  before_action :authenticate_user!
  before_action :set_cart, only: [:new, :create]

  def show
    # TODO: deny access to orders of other users
    @order = Order.find(params[:id])
  end

  def new
    if @cart.line_items.empty?
      redirect_to shop_url, notice: "Your cart is empty."
      return
    end

    @order = Order.new
  end

  def create
    @order = current_user.orders.build(order_params)

    if @order.save
      # Move items from cart to order
      @order.add_line_items_from_cart(@cart.id)

      # Destroy the cart and reset the session cart_id
      @cart.destroy
      session[:cart_id] = nil

      # Deliver order confirmation email
      OrderConfirmation.send_order_confirmation(current_user, @order).deliver_now

      # Redirect and confirmation notice
      redirect_to @order, notice: "Thank you for your order!"
    else
      render :new
    end
  end

  private

  def order_params
    params.require(:order).permit(:shipping_name, :shipping_address, :payment_type)
  end
end

app/controllers/storefront_controller.rb
class StorefrontController < ApplicationController

  def home
  end

  def index
    if params[:search]
      @products = Product.search_by_name_or_description(params[:search])
      if @products.empty?
        flash.now[:notice] = "No result found for \"#{params[:search]}\", showing all products."
        @products = Product.all
      end
    elsif params[:category_id]
      @category = Category.find(params[:category_id])
      @products = Product.where(category: @category)
    else
      @products = Product.all
    end
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/brands_helper.rb
module BrandsHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/line_items_helper.rb
module LineItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/storefront_helper.rb
module StorefrontHelper
end

app/views/layouts/_admin_links.html.erb
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Admin <span class="caret"></span></a>
  <ul class="dropdown-menu">
    <li><%= link_to "Brands", admin_brands_path %></li>
    <li><%= link_to "Categories", admin_categories_path %></li>
    <li><%= link_to "Products", admin_products_path %></li>
  </ul>
</li>

app/views/layouts/_messages.html.erb
<% if notice %>
  <div class="alert alert-success" role="alert">
    <p><%= notice %></p>
  </div>
<% elsif alert %>
  <div class="alert alert-danger" role="alert">
    <p><%= alert %></p>
  </div>
<% end %>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to fa_icon("paw", class: "fa-lg"), root_path, class: "navbar-brand" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <%= render 'layouts/navbar_links' %>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/_navbar_links.html.erb
<ul class="nav navbar-nav">
  <!-- Shop Dropdown -->
  <li class="dropdown">
    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Shop <span class="caret"></span></a>
    <ul class="dropdown-menu">

      <!-- Loop through each category to show name and custom params for shop link -->
      <% Category.order(:name).each do |category| %>
        <li><%= link_to category.name.titleize, shop_path(category_id: category.id) %></li>
      <% end %>

      <!-- Separate section for all products (no params) -->
      <li role="separator" class="divider"></li>
      <li><%= link_to 'All Products', shop_path %></li>
    </ul>
  </li>

  <li><%= link_to 'About', about_path %></li>
</ul>

<ul class="nav navbar-nav navbar-right">
  <!-- Shopping Cart link -->
  <% if session[:cart_id] %>
    <li><%= link_to fa_icon("shopping-cart", text: "Cart"), edit_cart_path %></li>
  <% end %>

  <!-- Admin Dropdown -->
  <% if user_signed_in? && current_user.admin %>
    <%= render 'layouts/admin_links' %>
  <% end %>

  <!-- Auth Links -->
  <% if user_signed_in? %>
    <li><%= link_to fa_icon('gear', text: 'Account'), edit_user_registration_path %></li>
    <li><%= link_to fa_icon('sign-out', text: 'Sign Out'), destroy_user_session_path, method: :delete %></li>
  <% else %>
    <li><%= link_to 'Sign Up!', new_user_registration_path %></li>
    <li><%= link_to fa_icon('sign-in', text: 'Log In'), new_user_session_path %></li>
  <% end %>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Merchant</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= render 'layouts/navbar' %>

<div class="container">
  <%= render 'layouts/messages' %>
  <%= yield %>
</div>

</body>
</html>

app/views/order_confirmation/send_order_confirmation.html.erb
<h1>Thank you for your order, <%= @user.email %>!</h1>

<p>Your order number is <%= @order.id %> and your total was <%= number_to_currency @order.subtotal %>.</p>

app/views/order_confirmation/send_order_confirmation.text.erb
Thank you for your order, <%= @user.email %>!

-------------------------------------------------------

Your order number is <%= @order.id %> and your total was <%= number_to_currency @order.subtotal %>.